// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal.proto

package dssproto

import (
	dssproto "InterUSS-Platform/pkg/dssproto"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Specification of a geographic area that a client is interested in on an ongoing basis (e.g., “planning area”).  Internal to the DSS.
type InternalSubscription struct {
	// If set, this Subscription will not generate any notifications before this time.  RFC 3339 format, per OpenAPI specification.
	Begins   *timestamp.Timestamp `protobuf:"bytes,1,opt,name=begins,proto3" json:"begins,omitempty"`
	Callback string               `protobuf:"bytes,2,opt,name=callback,proto3" json:"callback,omitempty"`
	// If set, this subscription will be automatically removed after this time.  RFC 3339 format, per OpenAPI specification.
	Expires *timestamp.Timestamp `protobuf:"bytes,3,opt,name=expires,proto3" json:"expires,omitempty"`
	// Unique identifier for this subscription.
	Id                string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	NotificationIndex int32  `protobuf:"varint,5,opt,name=notification_index,json=notificationIndex,proto3" json:"notification_index,omitempty"`
	// Assigned by the DSS based on creating client’s ID (via access token).  Used for restricting mutation and deletion operations to owner.
	Owner string `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	// A versioning string which can be used for read-modify-write operations to maintain idempotency.
	Version   string               `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Cells     []*S2Cell            `protobuf:"bytes,8,rep,name=cells,proto3" json:"cells,omitempty"`
	Footprint *dssproto.GeoPolygon `protobuf:"bytes,9,opt,name=footprint,proto3" json:"footprint,omitempty"`
	// Maximum bounding altitude of this volume.
	AltitudeHi float32 `protobuf:"fixed32,10,opt,name=altitude_hi,json=altitudeHi,proto3" json:"altitude_hi,omitempty"`
	// Minimum bounding altitude of this volume.
	AltitudeLo           float32  `protobuf:"fixed32,11,opt,name=altitude_lo,json=altitudeLo,proto3" json:"altitude_lo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalSubscription) Reset()         { *m = InternalSubscription{} }
func (m *InternalSubscription) String() string { return proto.CompactTextString(m) }
func (*InternalSubscription) ProtoMessage()    {}
func (*InternalSubscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{0}
}

func (m *InternalSubscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalSubscription.Unmarshal(m, b)
}
func (m *InternalSubscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalSubscription.Marshal(b, m, deterministic)
}
func (m *InternalSubscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalSubscription.Merge(m, src)
}
func (m *InternalSubscription) XXX_Size() int {
	return xxx_messageInfo_InternalSubscription.Size(m)
}
func (m *InternalSubscription) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalSubscription.DiscardUnknown(m)
}

var xxx_messageInfo_InternalSubscription proto.InternalMessageInfo

func (m *InternalSubscription) GetBegins() *timestamp.Timestamp {
	if m != nil {
		return m.Begins
	}
	return nil
}

func (m *InternalSubscription) GetCallback() string {
	if m != nil {
		return m.Callback
	}
	return ""
}

func (m *InternalSubscription) GetExpires() *timestamp.Timestamp {
	if m != nil {
		return m.Expires
	}
	return nil
}

func (m *InternalSubscription) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InternalSubscription) GetNotificationIndex() int32 {
	if m != nil {
		return m.NotificationIndex
	}
	return 0
}

func (m *InternalSubscription) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *InternalSubscription) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *InternalSubscription) GetCells() []*S2Cell {
	if m != nil {
		return m.Cells
	}
	return nil
}

func (m *InternalSubscription) GetFootprint() *dssproto.GeoPolygon {
	if m != nil {
		return m.Footprint
	}
	return nil
}

func (m *InternalSubscription) GetAltitudeHi() float32 {
	if m != nil {
		return m.AltitudeHi
	}
	return 0
}

func (m *InternalSubscription) GetAltitudeLo() float32 {
	if m != nil {
		return m.AltitudeLo
	}
	return 0
}

type S2Cell struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level                int32    `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2Cell) Reset()         { *m = S2Cell{} }
func (m *S2Cell) String() string { return proto.CompactTextString(m) }
func (*S2Cell) ProtoMessage()    {}
func (*S2Cell) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{1}
}

func (m *S2Cell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2Cell.Unmarshal(m, b)
}
func (m *S2Cell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2Cell.Marshal(b, m, deterministic)
}
func (m *S2Cell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2Cell.Merge(m, src)
}
func (m *S2Cell) XXX_Size() int {
	return xxx_messageInfo_S2Cell.Size(m)
}
func (m *S2Cell) XXX_DiscardUnknown() {
	xxx_messageInfo_S2Cell.DiscardUnknown(m)
}

var xxx_messageInfo_S2Cell proto.InternalMessageInfo

func (m *S2Cell) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *S2Cell) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func init() {
	proto.RegisterType((*InternalSubscription)(nil), "dssproto.InternalSubscription")
	proto.RegisterType((*S2Cell)(nil), "dssproto.S2Cell")
}

func init() { proto.RegisterFile("internal.proto", fileDescriptor_41f4a519b878ee3b) }

var fileDescriptor_41f4a519b878ee3b = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x6f, 0x9c, 0x30,
	0x10, 0xc5, 0xc5, 0x6e, 0xd8, 0x3f, 0x83, 0x14, 0xb5, 0x16, 0x07, 0x0b, 0x55, 0x0a, 0xca, 0xa1,
	0xe2, 0x12, 0x90, 0x68, 0xbf, 0x41, 0x0f, 0xed, 0x4a, 0x3d, 0x44, 0xd0, 0x9e, 0x23, 0x03, 0x86,
	0x8e, 0xe2, 0xf5, 0x20, 0xdb, 0x9b, 0xa6, 0x1f, 0xa9, 0xdf, 0xb2, 0xc2, 0x40, 0xd3, 0x9c, 0x7a,
	0xe3, 0xcd, 0xfc, 0xf4, 0xde, 0xf0, 0x0c, 0xd7, 0xa8, 0x9d, 0x34, 0x5a, 0xa8, 0x7c, 0x34, 0xe4,
	0x88, 0x1d, 0x3a, 0x6b, 0xfd, 0x57, 0xf2, 0x6e, 0x20, 0x1a, 0x94, 0x2c, 0xc4, 0x88, 0x85, 0xd0,
	0x9a, 0x9c, 0x70, 0x48, 0xda, 0xce, 0x5c, 0x72, 0xb3, 0x6c, 0xbd, 0x6a, 0x2e, 0x7d, 0xe1, 0xf0,
	0x2c, 0xad, 0x13, 0xe7, 0x71, 0x01, 0xb2, 0xd3, 0x64, 0xfc, 0xbd, 0xae, 0xef, 0xee, 0x95, 0x70,
	0x3d, 0x99, 0x73, 0x31, 0x3e, 0x0e, 0xc5, 0x6a, 0x3f, 0xd9, 0xce, 0xe4, 0xed, 0xef, 0x2d, 0xc4,
	0xa7, 0xe5, 0x8a, 0xfa, 0xd2, 0xd8, 0xd6, 0xe0, 0x38, 0x45, 0xb1, 0x12, 0x76, 0x8d, 0x1c, 0x50,
	0x5b, 0x1e, 0xa4, 0x41, 0x16, 0x95, 0x49, 0x3e, 0x87, 0xe6, 0x6b, 0x68, 0xfe, 0x6d, 0x0d, 0xad,
	0x16, 0x92, 0x25, 0x70, 0x68, 0x85, 0x52, 0x8d, 0x68, 0x1f, 0xf9, 0x26, 0x0d, 0xb2, 0x63, 0xf5,
	0x57, 0xb3, 0x8f, 0xb0, 0x97, 0xcf, 0x23, 0x1a, 0x69, 0xf9, 0xf6, 0xbf, 0x86, 0x2b, 0xca, 0xae,
	0x61, 0x83, 0x1d, 0xbf, 0xf2, 0x5e, 0x1b, 0xec, 0xd8, 0x1d, 0x30, 0x4d, 0x0e, 0x7b, 0x6c, 0x7d,
	0x21, 0x0f, 0xa8, 0x3b, 0xf9, 0xcc, 0xc3, 0x34, 0xc8, 0xc2, 0xea, 0xed, 0xbf, 0x9b, 0xd3, 0xb4,
	0x60, 0x31, 0x84, 0xf4, 0x53, 0x4b, 0xc3, 0x77, 0xde, 0x61, 0x16, 0x8c, 0xc3, 0xfe, 0x49, 0x1a,
	0x8b, 0xa4, 0xf9, 0xde, 0xcf, 0x57, 0xc9, 0xde, 0x43, 0xd8, 0x4a, 0xa5, 0x2c, 0x3f, 0xa4, 0xdb,
	0x2c, 0x2a, 0xdf, 0xe4, 0x6b, 0x63, 0x79, 0x5d, 0x7e, 0x92, 0x4a, 0x55, 0xf3, 0x9a, 0x95, 0x70,
	0xec, 0x89, 0xdc, 0x68, 0x50, 0x3b, 0x7e, 0xf4, 0xbf, 0x13, 0xbf, 0xb0, 0x9f, 0x25, 0xdd, 0x93,
	0xfa, 0x35, 0x90, 0xae, 0x5e, 0x30, 0x76, 0x03, 0x91, 0x50, 0x0e, 0xdd, 0xa5, 0x93, 0x0f, 0x3f,
	0x90, 0x43, 0x1a, 0x64, 0x9b, 0x0a, 0xd6, 0xd1, 0x17, 0x7c, 0x05, 0x28, 0xe2, 0xd1, 0x6b, 0xe0,
	0x2b, 0xdd, 0xe6, 0xb0, 0x9b, 0xcf, 0x58, 0x6a, 0x99, 0x1e, 0xe6, 0xca, 0xd7, 0x12, 0x43, 0xa8,
	0xe4, 0x93, 0x54, 0xbe, 0xf5, 0xb0, 0x9a, 0x45, 0xb3, 0xf3, 0xe7, 0x7c, 0xf8, 0x13, 0x00, 0x00,
	0xff, 0xff, 0xb4, 0xee, 0x63, 0xdf, 0x67, 0x02, 0x00, 0x00,
}
